movie_project/movie_app/urls.py
from django.urls import path
from . import views
app_name='movie_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:m_id>/',views.detail,name='detail'),
    path('add/',views.add,name="add"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movie_project/movie_project/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_url=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movie_project/movie_app/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from . models import Movie
# Create your views here.
def index(request):
    mve=Movie.objects.all()
    dict={
        'movie_list':mve
    }
    return render(request,"index.html",dict)
def detail(request,m_id):
    mve=Movie.objects.get(id=m_id)
    return render(request,"detail.html",{'dict':mve})

def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"edit.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"update.html",{'movie':movie,'form':form})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

movie_project/templates/delete.html
{% extends 'style.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    Are you sure???
    <input type="submit" value="DELETE">
    <a class="btn-btn-dark" href="/">BACK</a>
</form>
{% endblock %}

movie_project/templates/detail.html
{% extends 'style.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <img  src="{{dict.img.url}}" width="400" height ="500"><br>
        </div>
        <div class="col-md-4">
            <h1>{{dict.name}}</h1><br>
            <h5>{{dict.desc}}</h5><br>
            <h5>{{dict.year}}</h5>
            <a class="btn btn-secondary" href="{% url 'movie_app:update' dict.id %}">UPDATE</a>
            <a class="btn btn-danger" href="{% url 'movie_app:delete' dict.id %}">DELETE</a>
            <a class="btn btn-success" href="{% url 'movie_app:index' %}">HOME</a>
        </div>
    </div>
</div>

{% endblock %}

movie_project/templates/edit.html
{% extends 'style.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Movie Name</label>
    <input type="text" name="name" placeholder="Movie Name"><br>
    <label>Description</label>
    <input type="text" name="desc" placeholder="About Movie"><br>
    <label>Movie Relese year</label>
    <input type="text" name="year" placeholder="Release Year"><br>
    <label>Movie Poster</label>
    <input type="file" name="img"><br>
    <input type="submit" value="Add Movie">
    <a href="/">HOME</a >
</form>
{% endblock %}

movie_project/templates/index.html
{% extends 'style.html' %}
{% block body %}
<a class="btn btn-primary" href="{% url 'movie_app:add' %}">ADD MOVIE</a><br><br>

<div class="container">
    <div class="row mx-auto" >
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card">
                 <img class="card-img-top" src="{{i.img.url}}" alt="refresh" width="270" height="300">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="">{{i.desc}}</p>
                    <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-primary">Read more</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
<!--<img src="{{i.img.url}}" width="100" height="140">-->
<!--<a href="{% url 'movie_app:detail' i.id %}"> <t> <strong>{{i.name}}</strong><br>-->

movie_project/templates/style.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
  Online Movies
  </a>
</nav><br>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/templates/update.html
{% extends 'style.html' %}
{% block body %}
<form style="background-color:pink;" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit" value="update">UPDATE</button>
    <a class="btn btn-secondary" href="{% url 'movie_app:index' %}">HOME</a>
</form>
{% endblock %}




















<!-- xmlns="http://www.w3.org/1999/html"-->